---
- name: Create Twinbiot Cluster
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: create twinbiot-cluster
      shell: |
        gcloud beta container --project "guminator" clusters create "twinbiot-cluster" --zone "us-central1-b" --no-enable-basic-auth --cluster-version "1.17.15-gke.800" --machine-type "e2-small" --image-type "cos_containerd" --disk-type "pd-standard" --disk-size "20" --metadata disable-legacy-endpoints=true --scopes "https://www.googleapis.com/auth/devstorage.read_only","https://www.googleapis.com/auth/logging.write","https://www.googleapis.com/auth/monitoring","https://www.googleapis.com/auth/servicecontrol","https://www.googleapis.com/auth/service.management.readonly","https://www.googleapis.com/auth/trace.append" --preemptible --num-nodes "2" --enable-stackdriver-kubernetes --enable-ip-alias --network "projects/guminator/global/networks/default" --subnetwork "projects/guminator/regions/us-central1/subnetworks/default" --default-max-pods-per-node "110" --no-enable-master-authorized-networks --addons HorizontalPodAutoscaling,HttpLoadBalancing --enable-autoupgrade --enable-autorepair --max-surge-upgrade 1 --max-unavailable-upgrade 0

    - name: twinbiot-cluster auth
      shell: |
        gcloud container clusters get-credentials twinbiot-cluster --zone us-central1-b --project guminator
        # gcloud compute disks create --size=10GB --zone=us-central1-b gce-nfs-disk
