apiVersion: v1
kind: Service
metadata:
  name: ca-org1
  labels:
    app: ca-org1
spec:
  ports:
  - port: 7054
    name: ca-org1
  clusterIP: None
  selector:
    app: ca-org1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ca-org1
spec:
  selector:
    matchLabels:
      app: ca-org1 # Label selector that determines which Pods belong to the StatefulSet
                 # Must match spec: template: metadata: labels
  serviceName: "ca-org1"
  replicas: 1
  template:
    metadata:
      labels:
        app: ca-org1 # Pod template's label selector
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name:  ca-org1
        image: gcr.io/guminator/ca-server:1.1
        command: ["sh", "-c", "fabric-ca-server start -b admin:adminpw -d --port 7054"]
        env:
          - name: FABRIC_CA_HOME
            value: /fabric/config/organizations/fabric-ca/org1
          - name: FABRIC_CA_SERVER_CA_NAME
            value: ca-org1
          - name: FABRIC_CA_SERVER_PORT
            value: "7054"
          - name: FABRIC_CA_SERVER_CSR_CN
            value: "ca-org1"
          - name: FABRIC_CA_SERVER_CSR_HOSTS
            value: ca-org1
          - name: FABRIC_CA_SERVER_TLS_ENABLED
            value: "true"
          #- name: FABRIC_CA_SERVER_TLS_CERTFILE
          #  value: /var/hyperledger/config/organizations/peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem
          #- name: FABRIC_CA_SERVER_TLS_KEYFILE
          #  value: /var/hyperledger/config/organizations/peerOrganizations/org1.example.com/ca/priv_sk
        ports:
        - containerPort: 7054
          name: ca-org1
        volumeMounts:
        #- name: ca-org1
        #  mountPath: /var/hyperledger/config/organizations/fabric-ca/org1
        - name: fabric-config
          mountPath: /fabric
      volumes:
      - name: fabric-config
        persistentVolumeClaim:
          claimName: fabric
  #volumeClaimTemplates:
  #- metadata:
  #    name: ca-org1
  #  spec:
  #    accessModes: [ "ReadWriteOnce" ]
  #    resources:
  #      requests:
  #        storage: 1Gi
