apiVersion: v1
kind: Service
metadata:
  name: ca-orderer
  labels:
    app: ca-orderer
spec:
  ports:
  - port: 9054
    name: ca-orderer
  clusterIP: None
  selector:
    app: ca-orderer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ca-orderer
spec:
  selector:
    matchLabels:
      app: ca-orderer # Label selector that determines which Pods belong to the StatefulSet
                 # Must match spec: template: metadata: labels
  serviceName: "ca-orderer"
  replicas: 1
  template:
    metadata:
      labels:
        app: ca-orderer # Pod template's label selector
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name:  ca-orderer
        image: gcr.io/guminator/ca-server:1.1
        
        command: ["sh", "-c", "fabric-ca-server start -b admin:adminpw -d --port 9054"]
        env:
          - name: FABRIC_CA_HOME
            value: /fabric/config/organizations/fabric-ca/ordererOrg
          - name: FABRIC_CA_SERVER_CA_NAME
            value: ca-orderer
          - name: FABRIC_CA_SERVER_CSR_CN
            value: "ca-orderer"
          - name: FABRIC_CA_SERVER_CSR_HOSTS
            value: ca-orderer
          - name: FABRIC_CA_SERVER_PORT
            value: "9054"
          - name: FABRIC_CA_SERVER_TLS_ENABLED
            value: "true"
          #- name: FABRIC_CA_SERVER_TLS_CERTFILE
          #  value: /fabric/config/hyperledger/config/organizations/ordererOrganizations/example.com/ca/ca.example.com-cert.pem
          #- name: FABRIC_CA_SERVER_TLS_KEYFILE
          #  value: /fabric/config/organizations/ordererOrganizations/example.com/ca/priv_sk
        ports:
        - containerPort: 9054
          name: ca-orderer
        volumeMounts:
  #      - name: ca-orderer
  #        mountPath:  /var/hyperledger/config/organizations/fabric-ca/ordererOrg
        - name: fabric-config
          mountPath: /fabric
      volumes:
      - name: fabric-config
        persistentVolumeClaim:
          claimName: fabric
  #volumeClaimTemplates:
  #- metadata:
  #    name: ca-orderer
  #  spec:
  #    accessModes: [ "ReadWriteOnce" ]
  #    resources:
  #      requests:
  #        storage: 5Gi
