apiVersion: v1
kind: Service
metadata:
  name: twinbiot-app
spec:
  type: LoadBalancer
  selector:
    app: twinbiot-app
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: twinbiot-app
spec:
  selector:
    matchLabels:
      app: twinbiot-app # Label selector that determines which Pods belong to the StatefulSet
                 # Must match spec: template: metadata: labels
  serviceName: "twinbiot-app"
  replicas: 1
  template:
    metadata:
      labels:
        app: twinbiot-app # Pod template's label selector
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: twinbiot-app
        image: gcr.io/guminator/twinbiot-app:v1.3
        ports:
        - containerPort: 8081
          name: app
        volumeMounts:
        - name: wallet
          mountPath: /app/wallet
        - name: fabric-config
          mountPath: /fabric
      volumes:
      - name: fabric-config
        persistentVolumeClaim:
          claimName: fabric

  volumeClaimTemplates:
  - metadata:
      name: wallet
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
