apiVersion: v1
kind: PersistentVolume
metadata:
  name: fabric
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.96.0.155
    path: "/"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fabric
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
