apiVersion: v1
kind: Service
metadata:
  name: ca-org2
  labels:
    app: ca-org2
spec:
  ports:
  - port: 8054
    name: ca-org2
  clusterIP: None
  selector:
    app: ca-org2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ca-org2
spec:
  selector:
    matchLabels:
      app: ca-org2 # Label selector that determines which Pods belong to the StatefulSet
                 # Must match spec: template: metadata: labels
  serviceName: "ca-org2"
  replicas: 1
  template:
    metadata:
      labels:
        app: ca-org2 # Pod template's label selector
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name:  ca-org2
        image: gcr.io/guminator/ca-server:1.0
        env:
          - name: FABRIC_CA_HOME
            value: /var/hyperledger/config/organizations/fabric-ca/org2
          - name: FABRIC_CA_SERVER_CA_NAME
            value: ca-org2
          - name: FABRIC_CA_SERVER_PORT
            value: "8054"
          - name: FABRIC_CA_SERVER_TLS_ENABLED
            value: "true"
        ports:
        - containerPort: 8054
          name: ca-org2
        volumeMounts:
        - name: ca-org2
          mountPath: /var/hyperledger/config/organizations/fabric-ca/org2
  volumeClaimTemplates:
  - metadata:
      name: ca-org2
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
