apiVersion: v1
kind: Service
metadata:
  name: ca-org1
  labels:
    app: ca-org1
spec:
  ports:
  - port: 7054
    name: ca-org1
  clusterIP: None
  selector:
    app: ca-org1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ca-org1
spec:
  selector:
    matchLabels:
      app: ca-org1 # Label selector that determines which Pods belong to the StatefulSet
                 # Must match spec: template: metadata: labels
  serviceName: "ca-org1"
  replicas: 1
  template:
    metadata:
      labels:
        app: ca-org1 # Pod template's label selector
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name:  ca-org1
        image: gcr.io/guminator/ca-server:1.0
        env:
          - name: FABRIC_CA_HOME
            value: /var/hyperledger/config/organizations/fabric-ca/org1
          - name: FABRIC_CA_SERVER_CA_NAME
            value: ca-org1
          - name: FABRIC_CA_SERVER_PORT
            value: "7054"
          - name: FABRIC_CA_SERVER_TLS_ENABLED
            value: "true"
        ports:
        - containerPort: 7054
          name: ca-org1
        volumeMounts:
        - name: ca-org1
          mountPath: /var/hyperledger/config/organizations/fabric-ca/org1
  volumeClaimTemplates:
  - metadata:
      name: ca-org1
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
