apiVersion: v1
kind: Pod
metadata:
  name: fabric-tools
spec:
  volumes:
  - name: fabric-config
    persistentVolumeClaim:
      claimName: fabric
  - name: dockersocket
    hostPath:
      path: /var/run/docker.sock
  containers:
    - name: fabrictools
      image: gcr.io/guminator/twinbiot-tools:1.0
      imagePullPolicy: Always
      command: ["sh", "-c", "sleep 48"]
      env:
      - name: TZ
        value: "America/Sao_Paulo"
      - name: FABRIC_CFG_PATH
        value: "/fabric"
      volumeMounts:
        - mountPath: /fabric
          name: fabric-config
        - mountPath: /host/var/run/docker.sock
          name: dockersocket
