apiVersion: v1
kind: Service
metadata:
  name: orderer-example-com
  labels:
    app: orderer-example-com
spec:
  ports:
  - port: 7050
    name: orderer
  clusterIP: None
  selector:
    app: orderer-example-com
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orderer-example-com
spec:
  selector:
    matchLabels:
      app: orderer-example-com # Label selector that determines which Pods belong to the StatefulSet
                 # Must match spec: template: metadata: labels
  serviceName: "orderer-example-com"
  replicas: 1
  template:
    metadata:
      labels:
        app: orderer-example-com # Pod template's label selector
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: orderer-example-com
        image: gcr.io/guminator/twinbiot-orderer:1.7
        env:
          - name: ORDERER_GENERAL_LISTENADDRESS
            value: 0.0.0.0
          #- name: FABRIC_CFG_PATH
          #  value: /var/hyperledger/config/configtx
          - name: ORDERER_GENERAL_LISTENPORT
            value: "7050"
          - name: ORDERER_GENERAL_GENESISFILE
            value: /var/hyperledger/config/system-genesis-block/genesis.block
          - name: ORDERER_GENERAL_GENESISMETHOD
            value: file
          - name: ORDERER_GENERAL_TLS_ENABLED
            value: "true"
          - name: ORDERER_GENERAL_LOCALMSPID
            value: OrdererMSP
          - name: ORDERER_GENERAL_LOCALMSPDIR
            value: /var/hyperledger/config/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp
          - name: FABRIC_LOGGING_SPEC
            value: INFO
          - name: ORDERER_GENERAL_TLS_CERTIFICATE
            value: /var/hyperledger/config/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
          - name: ORDERER_GENERAL_TLS_PRIVATEKEY
            value: /var/hyperledger/config/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.key
          - name: ORDERER_GENERAL_TLS_ROOTCAS
            value: /var/hyperledger/config/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt
          - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
            value: /var/hyperledger/config/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
          - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
            value: /var/hyperledger/config/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.key
          - name: ORDERER_GENERAL_CLUSTER_ROOTCAS
            value: "[/var/hyperledger/config/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt]"
        ports:
        - containerPort: 7050
          name: orderer
        volumeMounts:
        - name: orderer-ledger
          mountPath: /var/hyperledger/production/orderer
  volumeClaimTemplates:
  - metadata:
      name: orderer-ledger
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
