# YAML for launching the orderer
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: twinbiot-org1
  labels:
    app: twinbiot-org1
spec:
  serviceName: twinbiot-org1
  replicas: 1
  selector:
    matchLabels:
      app: twinbiot-org1
  template:
    metadata:
      labels:
        app: twinbiot-org1
    spec:
      containers:
      - name: twinbiot-org1
        # Image used
        image: gcr.io/guminator/twinbiot-org1:1.0
        # Uncomment the following during development/testing of the image
        # imagePullPolicy: Always
        env:
          - name: FABRIC_CFG_PATH
            value: /var/hyperledger/config
          - name: FABRIC_LOGGING_SPEC
            value: DEBUG
          - name: ORDERER_ADDRESS
            value: orderer-example:7050
          - name: ORG_CONTEXT
            value: org1.example.com
          - name: CORE_PEER_ADDRESS
            value: 0.0.0.0:7051
        volumeMounts:
        - mountPath: /var/hyperledger/production
          name: peer0-org1
        - name: dockersock
          mountPath: /var/run/docker.sock
        ports:
        - containerPort: 7051
        - containerPort: 7052
        - containerPort: 9443
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
  volumeClaimTemplates:
  - metadata:
      name: peer0-org1
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: general
      resources:
        requests:
          storage: 1Gi

---
kind: Service
apiVersion: v1
metadata:
  name: peer0-org1
spec:
  selector:
    app: "twinbiot-org1"
  ports:
  - name: "grpc"
    port: 7051
    protocol: TCP
    targetPort: 7051
  - name: "chaincode"
    port: 7052
    protocol: TCP
    targetPort: 7052
  - name: "ops"
    port: 9443
    protocol: TCP
    targetPort: 9443

