PeerOrgs:
  - Name: Org1
    Domain: org1.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - "{{.Hostname}}-org1-example-com"
    Users:
      Count: 1