apiVersion: v1
kind: PersistentVolume
metadata:
  name: fabric-config
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.96.0.2 
    path: "/fabric"
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fabric-config
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi
