---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orderer.example.com
  name: orderer.example.com
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderer.example.com
  template:
    metadata:
      labels:
        app: orderer.example.com
    spec:
      containers:
      - image: hyperledger/fabric-orderer:2.2.1
        imagePullPolicy: IfNotPresent
        name: fabric-orderer
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric
        env:
        - name: FABRIC_LOGGING_SPEC
          value: DEBUG
        - name: ORDERER_GENERAL_GENESISFILE
          value: /var/hyperledger/orderer/genesis.block
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: file
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: 0.0.0.0
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: /var/hyperledger/orderer/msp
        - name: ORDERER_GENERAL_LOCALMSPID
          value: OrdererMSP
        - name: ORDERER_GENERAL_TLS_CERTIFICATE
          value: /var/hyperledger/orderer/tls/server.crt
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "true"
        - name: ORDERER_GENERAL_TLS_PRIVATEKEY
          value: /var/hyperledger/orderer/tls/server.key
        - name: ORDERER_GENERAL_TLS_ROOTCAS
          value: "[/var/hyperledger/orderer/tls/ca.crt]"
        - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
          value: /var/hyperledger/orderer/tls/server.crt
        - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
          value: /var/hyperledger/orderer/tls/server.key
        - name: ORDERER_GENERAL_CLUSTER_ROOTCAS
          value: "[/var/hyperledger/orderer/tls/ca.crt]"
        volumeMounts:
        - mountPath: /var/hyperledger/production/orderer
          name: fabric-config
          subPath: orderer 
        - mountPath: /var/hyperledger/orderer/msp
          subPath: organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp
          name: fabric-config
        - mountPath: /var/hyperledger/orderer/tls
          subPath: organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls
          name: fabric-config
        - mountPath: /var/hyperledger/orderer/genesis.block
          subPath: genesis.block
          name: fabric-config
        ports:
        - containerPort: 7050
        readinessProbe:
          tcpSocket:
            port: 7050
      volumes:
      - name: fabric-config
        persistentVolumeClaim:
          claimName: fabric

---
kind: Service
apiVersion: v1
metadata:
  name: orderer-example-com
spec:
  selector:
    app: "orderer.example.com"
  ports:
  - name: "grpc"
    port: 7050
    protocol: TCP
    targetPort: 7050
---



          
