---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: peer0.org2.example.com
  name: peer0.org2.example.com
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: peer0.org2.example.com
  template:
    metadata:
      labels:
        app: peer0.org2.example.com
    spec:
      containers:
      - image: hyperledger/fabric-peer:2.2.1
        name: fabric-peer
        workingDir: /etc/hyperledger/fabric/
        command:
        env:
        - name: FABRIC_LOGGING_SPEC
          value: INFO
        - name: CORE_PEER_ADDRESS
          value: "peer0-org2-example-com:7051"
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: "peer0-org2-example-com:7051"
        - name: CORE_PEER_LISTENADDRESS
          value: "0.0.0.0:7051"
        - name: CORE_PEER_CHAINCODELISTENADDRESS
          value: "0.0.0.0:7052"
        - name: CORE_PEER_LOCALMSPID
          value: "Org1MSP"
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: "peer0-org2-example-com:7051"
        - name: CORE_PEER_GOSSIP_USELEADERELECTION
          value: "true"
        - name: CORE_PEER_PROFILE_ENABLED
          value: true
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric/
        - name: CORE_PEER_TLS_CERT_FILE
          value: /etc/hyperledger/fabric/tls/server.crt
        - name: CORE_PEER_TLS_KEY_FILE
          value: /etc/hyperledger/fabric/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /etc/hyperledger/fabric/tls/ca.crt
        - name: ORDERER_ADDRESS
          value: orderer-example-com:7050
        volumeMounts:
        - mountPath: /var/hyperledger/production/
          name: peer
        - mountPath: /etc/hyperledger/fabric/msp/
          subPath: organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/
          name: fabric-config
        - mountPath: /etc/hyperledger/fabric/tls/
          subPath: organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/
          name: fabric-config
        - mountPath: /host/var/run/docker.sock

        ports:
        - containerPort: 7051
        - containerPort: 7052
        imagePullPolicy: IfNotPresent
        readinessProbe:
          tcpSocket:
            port: 7051
          initialDelaySeconds: 2
          timeoutSeconds: 5
          periodSeconds: 5
          failureThreshold: 10
      volumes:
      - name: fabric-config
        persistentVolumeClaim:
          claimName: fabric-config
      - name: peer
        persistentVolumeClaim:
          claimName: peer0.org2.example.com
      - name: dockersocket
        hostPath: /var/run/docker.sock
---
kind: Service
apiVersion: v1
metadata:
  name: peer0-org2-example-com
spec:
  selector:
    app: "peer0.org2.example.com"
  ports:
  - name: "grpc"
    port: 7051
    protocol: TCP
    targetPort: 7051
  - name: "chaincode"
    port: 7052
    protocol: TCP
    targetPort: 7052

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: peer0.org2.example.com
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.96.8.25
    path: "/"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: peer0.org2.example.com
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
