---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: peer0.org1.example.com
  name: peer0.org1.example.com
spec:
  selector:
    matchLabels:
      app: peer0.org1.example.com
  template:
    metadata:
      labels:
        app: peer0.org1.example.com
    spec:
      containers:
      - image: k8scc:latest
        name: fabric-peer
