apiVersion: v1
kind: PersistentVolume
metadata:
  name: fabric-pv
  labels:
    type: local
    name: fabricicles
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server
    path: "/"
    readOnly: false

    
