apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-orderer
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ca-orderer
  template:
    metadata:
      labels:
        name: ca-orderer
    spec:
      volumes:
      - name: fabricfiles
        persistentVolumeClaim:
          claimName: fabric

      containers:
      - name: orderer
        image: hyperledger/fabric-ca:1.4.9
        command: ["sh", "-c", "fabric-ca-server start -b admin:adminpw -d"]
         ports:
        - containerPort: 9054
        env:
        - name: FABRIC_CA_HOME
          value: /fabric/config/organizations/fabric-ca/ordererOrg
        - name: FABRIC_CA_SERVER_CA_NAME
          value: ca-orderer
        - name: FABRIC_CA_SERVER_PORT
          value: "9054"
        - name: FABRIC_CA_SERVER_TLS_ENABLED
          value: "true"
        volumeMounts:
        - mountPath: /fabric
          name: fabricfiles

  ---

  apiVersion: v1
  kind: Service
  metadata:
    name: ca-orderer
    labels:
      run: ca-orderer
  spec:
    type: ClusterIP
    selector:
      name: ca-orderer
    ports:
    - protocol: TCP
      port: 9054
      name: grpc
          
